# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('description', models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici')),
                ('address', models.TextField(blank=True, max_length=250, verbose_name='Contact')),
                ('stars', models.IntegerField(default=1, verbose_name='Stele')),
                ('price', models.CharField(max_length=15, verbose_name='Pret(RON)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('visitors_no', models.IntegerField(default=0, verbose_name='Numar de vizitatori')),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PostOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('description', models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PostOwnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('description', models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('description', models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='postowner',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='BookingManager.PostOwnerType'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='BookingManager.PostOwner', verbose_name='Proprietar'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='BookingManager.PostType'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('name', 'post_type')]),
        ),
    ]
