# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='0', max_length=15, unique=True, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
