# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clasificare', to='BookingManager.PostType'),
        ),
    ]
