# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0002_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True, max_length=250, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(default='0.0', max_length=10, unique=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.CharField(default='1', max_length=10, unique=True, verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitors_no',
            field=models.CharField(default='0', max_length=10, unique=True, verbose_name='Number of visitors'),
        ),
    ]
