# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0003_auto_20170527_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=15, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default=1, verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitors_no',
            field=models.IntegerField(default=0, unique=True, verbose_name='Number of visitors'),
        ),
    ]
