# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0004_auto_20170527_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visitors_no',
            field=models.IntegerField(default=0, verbose_name='Number of visitors'),
        ),
    ]
