# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0005_auto_20170527_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('description', models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici')),
            ],
        ),
        migrations.CreateModel(
            name='PostOwnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('description', models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=15, verbose_name='Pret(RON)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default=1, verbose_name='Stele'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitors_no',
            field=models.IntegerField(default=0, verbose_name='Numar de vizitatori'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='description',
            field=models.TextField(blank=True, default='-no-description-', max_length=1000, verbose_name='Caracteristici'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='postowner',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='BookingManager.PostOwnerType'),
        ),
    ]
