# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManager', '0006_auto_20170527_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postowner',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='postownertype',
            options={'ordering': ('name',)},
        ),
    ]
